### ISSUE TITLE
Paste.py giving Undesired Result

### ISSUE THREAD

**Issue by parzival979** [jashwanth0712/blockboard#3]
Paste.py in the web3 sub directory giving additional config text when it actually works, Otherwise It Just works normally giving the resource unavailable message

The Undesired Text is shown in Bold Below

(blockboard) parzival979@Potluris-MacBook-Air web3 % node main.js
**File clipboard_content.txt already exists
File clipboard_content.txt updated with contents: File clipboard_content.txt already exists
File clipboard_content.txt updated with contents: import subprocess**

import pyperclip

def execute_command(command):
    process = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()
    if error:
        return error.decode(utf-8)
    return output.decode(utf-8)

clipboard_data = pyperclip.paste()

print(clipboard_data)

if clipboard_data:
    pyperclip.copy(execute_command("node main.js --text {text}".format(text = clipboard_data)))
stdout: Uploading 1 files

**stdout: Content added with CID: bafybeihrf2yporm6ydibjsamovu4frivf5fpzqie3bd6iwkyozaetzgaem
child process exited with code 0
stdout: Uploading 1 files
stdout: Content added with CID: bafybeicdd3xkfu6wnzs4trypyspshzqyrdkccxuj53zyu4k25bmeybvsmy
child process exited with code 0**

**Comment by jashwanth0712** [comment]
Created a better algorithm to manage copy and paste and solved the issue
